export const charactersPercents = [
{ name: "mario", comboMoveType: "dash-first", percentWindow: [84, 98], tracker: 0 },
{ name: "donkey_kong", comboMoveType: "no-dash", percentWindow: [94, 133], tracker: 1 },
{ name: "link", comboMoveType: "", percentWindow: false, tracker: 2 },
{ name: "samus", comboMoveType: "no-dash", percentWindow: [92, 110], tracker: 3 },
{ name: "yoshi", comboMoveType: "no-dash", percentWindow: [88, 103], tracker: 4 },
{ name: "kirby", comboMoveType: "no-dash", percentWindow: [67, 94], tracker: 5 },
{ name: "fox", comboMoveType: "dash-first", percentWindow: [76, 79], tracker: 6 },
{ name: "pikachu", comboMoveType: "dash-first", percentWindow: [79, 84], tracker: 7 },
{ name: "luigi", comboMoveType: "no-dash", percentWindow: [88, false], tracker: 8 },
{ name: "ness", comboMoveType: "no-dash", percentWindow: [76, 94], tracker: 9 },
{ name: "captain_falcon", comboMoveType: "no-dash", percentWindow: [90, 104], tracker: 10 },
{ name: "purin", comboMoveType: "no-dash", percentWindow: [52, 89], tracker: 11 },
{ name: "peach", comboMoveType: "dash-first", percentWindow: [86, 94], tracker: 12 },
{ name: "koopa", comboMoveType: "no-dash", percentWindow: [107, 133], tracker: 13 },
{ name: "ice_climber", comboMoveType: "no-dash", percentWindow: [81, 99], tracker: 14 },
{ name: "sheik", comboMoveType: "dash-first", percentWindow: [84, 86], tracker: 15 },
{ name: "zelda", comboMoveType: "no-dash", percentWindow: [74, 92], tracker: 16 },
{ name: "dr_mario", comboMoveType: "no-dash", percentWindow: [86, 99], tracker: 17 },
{ name: "pichu", comboMoveType: "dash-first", percentWindow: [62, 77], tracker: 18 },
{ name: "falco", comboMoveType: "", percentWindow: false, tracker: 19 },
{ name: "marth", comboMoveType: "no-dash", percentWindow: [81, 96], tracker: 20 },
{ name: "lucina", comboMoveType: "no-dash", percentWindow: [81, 96], tracker: 21 },
{ name: "young_link", comboMoveType: "dash-first", percentWindow: [83, 85], tracker: 22 },
{ name: "ganondorf", comboMoveType: "no-dash", percentWindow: [91, 118], tracker: 23 },
{ name: "mewtwo", comboMoveType: "dash-first", percentWindow: [79, 90], tracker: 24 },
{ name: "roy", comboMoveType: "", percentWindow: false, tracker: 25 },
{ name: "chrom", comboMoveType: "", percentWindow: false, tracker: 26 },
{ name: "mr_game_and_watch", comboMoveType: "no-dash", percentWindow: [65, 89], tracker: 27 },
{ name: "meta_knight", comboMoveType: "dash-first", percentWindow: [81, 87], tracker: 28 },
{ name: "pit", comboMoveType: "dash-first", percentWindow: [92, 100], tracker: 29 },
{ name: "dark_pit", comboMoveType: "dash-first", percentWindow: [92, 100], tracker: 30 },
{ name: "zero_suit_samus", comboMoveType: "", percentWindow: false, tracker: 31 },
{ name: "wario", comboMoveType: "no-dash", percentWindow: [81, 108], tracker: 32 },
{ name: "snake", comboMoveType: "no-dash", percentWindow: [86, 114], tracker: 33 },
{ name: "ike", comboMoveType: "no-dash", percentWindow: [88, 112], tracker: 34 },
{ name: "pokemon_trainer", comboMoveType: "no-dash", percentWindow: [73, 81], tracker: 35 },
{ name: "diddy_kong", comboMoveType: "", percentWindow: false, tracker: 36 },
{ name: "lucas", comboMoveType: "no-dash", percentWindow: [76, 97], tracker: 37 },
{ name: "sonic", comboMoveType: "dash-first", percentWindow: [86, 95], tracker: 38 },
{ name: "dedede", comboMoveType: "no-dash", percentWindow: [97, 127], tracker: 39 },
{ name: "pikmin_and_olimar", comboMoveType: "no-dash", percentWindow: [67, 89], tracker: 40 },
{ name: "lucario", comboMoveType: "dash-first", percentWindow: [90, 98], tracker: 41 },
{ name: "robot", comboMoveType: "no-dash", percentWindow: [80, 99], tracker: 42 },
{ name: "toon_link", comboMoveType: "", percentWindow: false, tracker: 43 },
{ name: "wolf", comboMoveType: "", percentWindow: false, tracker: 44 },
{ name: "murabito", comboMoveType: "no-dash", percentWindow: [81, 97], tracker: 45 },
{ name: "rockman", comboMoveType: "no-dash", percentWindow: [85, 102], tracker: 46 },
{ name: "wii_fit_trainer", comboMoveType: "no-dash", percentWindow: [83, 101], tracker: 47 },
{ name: "rosetta_and_chiko", comboMoveType: "no-dash", percentWindow: [75, 92], tracker: 48 },
{ name: "little_mac", comboMoveType: "", percentWindow: false, tracker: 49 },
{ name: "gekkouga", comboMoveType: "dash-first", percentWindow: [86, 90], tracker: 50 },
{ name: "mii_fighter:brawler", comboMoveType: "", percentWindow: false, tracker: 83 },
{ name: "mii_fighter:gunner", comboMoveType: "no-dash", percentWindow: [84, 104], tracker: 82 },
{ name: "mii_fighter:fighter", comboMoveType: "no-dash", percentWindow: [82, 100], tracker: 81 },
{ name: "palutena", comboMoveType: "", percentWindow: false, tracker: 51 },
{ name: "pac_man", comboMoveType: "no-dash", percentWindow: [76, 97], tracker: 52 },
{ name: "reflet", comboMoveType: "no-dash", percentWindow: [83, 100], tracker: 53 },
{ name: "shulk", comboMoveType: "no-dash", percentWindow: [83, 102], tracker: 54 },
{ name: "koopa_jr", comboMoveType: "no-dash", percentWindow: [83, 112], tracker: 55 },
{ name: "duck_hunt", comboMoveType: "no-dash", percentWindow: [73, 93], tracker: 56 },
{ name: "ryu", comboMoveType: "no-dash", percentWindow: [89, 105], tracker: 57 },
{ name: "ken", comboMoveType: "no-dash", percentWindow: [89, 105], tracker: 58 },
{ name: "cloud", comboMoveType: "no-dash", percentWindow: [85, 100], tracker: 59 },
{ name: "kamui", comboMoveType: "no-dash", percentWindow: [84, 102], tracker: 60 },
{ name: "bayonetta", comboMoveType: "", percentWindow: false, tracker: 61 },
{ name: "inkling", comboMoveType: "dash-first", percentWindow: [86, 95], tracker: 62 },
{ name: "ridley", comboMoveType: "no-dash", percentWindow: [87, 116], tracker: 63 },
{ name: "simon", comboMoveType: "no-dash", percentWindow: [88, 112], tracker: 64 },
{ name: "richter", comboMoveType: "no-dash", percentWindow: [88, 112], tracker: 65 },
{ name: "king_k_rool", comboMoveType: "no-dash", percentWindow: [92, 131], tracker: 66 },
{ name: "shizue", comboMoveType: "no-dash", percentWindow: [73, 91], tracker: 67 },
{ name: "gaogaen", comboMoveType: "no-dash", percentWindow: [96, 114], tracker: 68 },
{ name: "packun_flower", comboMoveType: "no-dash", percentWindow: [83, 104], tracker: 69 },
{ name: "joker", comboMoveType: "no-dash", percentWindow: [81, 100], tracker: 70 },
{ name: "dq_hero", comboMoveType: "dash-first", percentWindow: [85, 86], tracker: 71 },
{ name: "banjo_and_kazooie", comboMoveType: "no-dash", percentWindow: [100, 121], tracker: 72 },
{ name: "terry", comboMoveType: "no-dash", percentWindow: [91, 109], tracker: 73 },
{ name: "byleth", comboMoveType: "dash-first", percentWindow: [92, 100], tracker: 74 },
{ name: "minmin", comboMoveType: "no-dash", percentWindow: [88, 108], tracker: 75 },
{ name: "steve", comboMoveType: "no-dash", percentWindow: [77, 93], tracker: 76 },
{ name: "sephiroth", comboMoveType: "no-dash", percentWindow: [79, 85], tracker: 77 },
{ name: "homura", comboMoveType: "no-dash", percentWindow: [84, 100], tracker: 78 },
{ name: "kazuya", comboMoveType: "no-dash", percentWindow: [94, 111], tracker: 79 },
{ name: "sora", comboMoveType: "dash-first", percentWindow: [76, 94], tracker: 80 }
  
  ];
